dado = input('Digite algo: ')
print(dado.isalpha())
print(dado.isalnum())
print(dado.isascii())
print(dado.isdigit())
print(dado.islower())
print(dado.isidentifier())
print(dado.isdecimal())
print(dado.isnumeric())
print(dado.isprintable())
print(dado.isspace())
